In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import urllib.request
import json

with urllib.request.urlopen("https://api.apify.com/v2/key-value-stores/ad2dUV2Kkxba6XhO1/records/LATEST?disableRedirect=true") as url:
    data = json.loads(url.read().decode())

In [17]:
df = pd.DataFrame(data['data']['daily'])

In [18]:
df

,2020-02-27,2020-02-28,2020-02-29,2020-03-01,2020-03-02,2020-03-03,2020-03-04,2020-03-05,2020-03-06,2020-03-07,...,2020-03-31,2020-04-01,2020-04-02,2020-04-03,2020-04-04,2020-04-05,2020-04-06,2020-04-07,2020-04-08,2020-04-09
c,"{'n': 0, 't': 0}","{'n': 0, 't': 0}","{'n': 0, 't': 0}","{'n': 3, 't': 3}","{'n': 0, 't': 3}","{'n': 2, 't': 5}","{'n': 0, 't': 5}","{'n': 3, 't': 8}","{'n': 11, 't': 19}","{'n': 7, 't': 26}",...,"{'n': 307, 't': 3308}","{'n': 281, 't': 3589}","{'n': 269, 't': 3858}","{'n': 332, 't': 4190}","{'n': 282, 't': 4472}","{'n': 115, 't': 4587}","{'n': 235, 't': 4822}","{'n': 195, 't': 5017}","{'n': 295, 't': 5312}",NaN
t,"{'n': 170, 't': 170}","{'n': 23, 't': 193}","{'n': 7, 't': 200}","{'n': 11, 't': 211}","{'n': 51, 't': 262}","{'n': 78, 't': 340}","{'n': 67, 't': 407}","{'n': 76, 't': 483}","{'n': 111, 't': 594}","{'n': 193, 't': 787}",...,"{'n': 6206, 't': 55017}","{'n': 5973, 't': 60990}","{'n': 6291, 't': 67281}","{'n': 6889, 't': 74170}","{'n': 6134, 't': 80304}","{'n': 4710, 't': 85014}","{'n': 6233, 't': 91247}","{'n': 7434, 't': 98681}","{'n': 8164, 't': 106845}",NaN
q,NaN,NaN,NaN,{'n': 35},{'n': 128},{'n': 165},{'n': 203},{'n': 259},{'n': 430},{'n': 807},...,{'n': 15341},{'n': 13764},{'n': 13293},{'n': 12995},{'n': 11956},{'n': 11867},{'n': 12182},{'n': 11298},{'n': 10792},NaN
r0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"{'n': 1.3, 'd': 1.4, 'x': 1.4}","{'n': 1.2, 'd': 1.3, 'x': 1.3}","{'n': 1.2, 'd': 1.2, 'x': 1.3}","{'n': 1.1, 'd': 1.2, 'x': 1.2}","{'n': 1.1, 'd': 1.1, 'x': 1.2}","{'n': 1, 'd': 1.1, 'x': 1.1}","{'n': 1.1, 'd': 1.1, 'x': 1.2}","{'n': 1, 'd': 1, 'x': 1.1}","{'n': 1, 'd': 1, 'x': 1.1}",NaN
h,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"{'t': 312, 'c': [70, '22,44 %'], 'h': [114, '2...","{'t': 342, 'c': [72, '21,05 %'], 'h': [136, '2...","{'t': 359, 'c': [77, '21,45 %'], 'h': [152, '2...","{'t': 380, 'c': [87, '22,89 %'], 'h': [173, '3...","{'t': 383, 'c': [86, '22,45 %'], 'h': [183, '3...","{'t': 391, 'c': [84, '21,48 %'], 'h': [188, '3...","{'t': 408, 'c': [86, '21,08 %'], 'h': [199, '3...","{'t': 432, 'c': [103, '23,84 %'], 'h': [219, '...","{'t': 440, 'c': [96, '21,82 %'], 'h': [239, '3...",NaN
d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"{'n': 7, 't': 36}","{'n': 8, 't': 44}","{'n': 5, 't': 49}","{'n': 8, 't': 57}","{'n': 8, 't': 65}","{'n': 12, 't': 77}","{'n': 7, 't': 84}","{'n': 9, 't': 93}","{'n': 12, 't': 105}","{'n': 7, 't': 112}"

In [21]:
daily = pd.DataFrame(df.T['c'])

In [25]:
df['c'][1]

KeyError: 'c'